// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebQLThiTracNghiem.Data;

#nullable disable

namespace WebQLThiTracNghiem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebQLThiTracNghiem.Models.CauHoi", b =>
                {
                    b.Property<int>("MaCauHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCauHoi"));

                    b.Property<int>("MaChuyenDe")
                        .HasColumnType("int");

                    b.Property<int>("MucDo")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaCauHoi");

                    b.ToTable("CauHoi");
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.ChiTietBaiLam", b =>
                {
                    b.Property<int>("MaLuotThi")
                        .HasColumnType("int");

                    b.Property<int>("MaCauHoi")
                        .HasColumnType("int");

                    b.Property<double>("DiemCau")
                        .HasColumnType("float");

                    b.Property<bool>("DungSai")
                        .HasColumnType("bit");

                    b.Property<int?>("MaDapAnChon")
                        .HasColumnType("int");

                    b.HasKey("MaLuotThi", "MaCauHoi");

                    b.ToTable("ChiTietBaiLam");
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.ChiTietDeThi", b =>
                {
                    b.Property<int>("MaDeThi")
                        .HasColumnType("int");

                    b.Property<int>("MaCauHoi")
                        .HasColumnType("int");

                    b.Property<double>("DiemCauHoi")
                        .HasColumnType("float");

                    b.HasKey("MaDeThi", "MaCauHoi");

                    b.ToTable("ChiTietDeThi");
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.ChuyenDe", b =>
                {
                    b.Property<int>("MaChuyenDe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuyenDe"));

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("int");

                    b.Property<string>("TenChuyenDe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChuyenDe");

                    b.ToTable("ChuyenDe");
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.DanhSachDuThi", b =>
                {
                    b.Property<int>("MaDotThi")
                        .HasColumnType("int");

                    b.Property<int>("MaHocSinh")
                        .HasColumnType("int");

                    b.Property<bool>("DuocPhepThi")
                        .HasColumnType("bit");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaDotThi", "MaHocSinh");

                    b.ToTable("DanhSachDuThi");
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.DapAn", b =>
                {
                    b.Property<int>("MaDapAn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDapAn"));

                    b.Property<bool>("LaDapAnDung")
                        .HasColumnType("bit");

                    b.Property<int>("MaCauHoi")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDapAn");

                    b.ToTable("DapAn");
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.DeThi", b =>
                {
                    b.Property<int>("MaDeThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDeThi"));

                    b.Property<int>("MaMonHoc")
                        .HasColumnType("int");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("TenDeThi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ThoiGianLamBai")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<bool>("TronCauHoi")
                        .HasColumnType("bit");

                    b.Property<bool>("TronDapAn")
                        .HasColumnType("bit");

                    b.HasKey("MaDeThi");

                    b.ToTable("DeThi");
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.DotThi", b =>
                {
                    b.Property<int>("MaDotThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDotThi"));

                    b.Property<int>("MaDeThi")
                        .HasColumnType("int");

                    b.Property<int>("SoLanThiToiDa")
                        .HasColumnType("int");

                    b.Property<string>("TenDotThi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDotThi");

                    b.ToTable("DotThi");
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.GiaoVien", b =>
                {
                    b.Property<int>("MaGiaoVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaoVien"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaGiaoVien");

                    b.ToTable("GiaoVien");

                    b.HasData(
                        new
                        {
                            MaGiaoVien = 1,
                            MaNguoiDung = 2,
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.HoSoCaNhan", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("HoSoCaNhan");
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.HocSinh", b =>
                {
                    b.Property<int>("MaHocSinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHocSinh"));

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("SoBaoDanh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaHocSinh");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("HocSinh");

                    b.HasData(
                        new
                        {
                            MaHocSinh = 1,
                            MaLop = 1,
                            MaNguoiDung = 3,
                            SoBaoDanh = "HS001",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.Lop", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<string>("KyHieuLop")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLop");

                    b.ToTable("Lop");

                    b.HasData(
                        new
                        {
                            MaLop = 1,
                            KyHieuLop = "12A1",
                            NamHoc = "2025-2026",
                            TenLop = "Lop 12A1"
                        });
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.LuotThi", b =>
                {
                    b.Property<int>("MaLuotThi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLuotThi"));

                    b.Property<int>("LanThi")
                        .HasColumnType("int");

                    b.Property<int>("MaDotThi")
                        .HasColumnType("int");

                    b.Property<int>("MaHocSinh")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiDiemBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiDiemNopBai")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaLuotThi");

                    b.ToTable("LuotThi");
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.MonHoc", b =>
                {
                    b.Property<int>("MaMonHoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaMonHoc"));

                    b.Property<string>("KyHieuMon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaMonHoc");

                    b.ToTable("MonHoc");

                    b.HasData(
                        new
                        {
                            MaMonHoc = 1,
                            KyHieuMon = "TOAN",
                            TenMonHoc = "Toan"
                        },
                        new
                        {
                            MaMonHoc = 2,
                            KyHieuMon = "LY",
                            TenMonHoc = "Vat ly"
                        },
                        new
                        {
                            MaMonHoc = 3,
                            KyHieuMon = "HOA",
                            TenMonHoc = "Hoa hoc"
                        },
                        new
                        {
                            MaMonHoc = 4,
                            KyHieuMon = "SINH",
                            TenMonHoc = "Sinh hoc"
                        },
                        new
                        {
                            MaMonHoc = 5,
                            KyHieuMon = "ANH",
                            TenMonHoc = "Tieng Anh"
                        });
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<int>("MaVaiTro")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDung");

                    b.HasData(
                        new
                        {
                            MaNguoiDung = 1,
                            MaVaiTro = 1,
                            MatKhau = "123",
                            NgayTao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin",
                            TrangThai = true
                        },
                        new
                        {
                            MaNguoiDung = 2,
                            MaVaiTro = 2,
                            MatKhau = "123",
                            NgayTao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "gv01",
                            TrangThai = true
                        },
                        new
                        {
                            MaNguoiDung = 3,
                            MaVaiTro = 3,
                            MatKhau = "123",
                            NgayTao = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "hs01",
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.NhatKyHeThong", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DoiTuongTacDong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MaBanGhiTacDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianThucHien")
                        .HasColumnType("datetime2");

                    b.HasKey("MaNhatKy");

                    b.ToTable("NhatKyHeThong");
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiTao")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaThongBao");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.ThongBaoNguoiNhan", b =>
                {
                    b.Property<int>("MaThongBao")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ThoiGianDoc")
                        .HasColumnType("datetime2");

                    b.HasKey("MaThongBao", "MaNguoiDung");

                    b.ToTable("ThongBaoNguoiNhan");
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.VaiTro", b =>
                {
                    b.Property<int>("MaVaiTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaVaiTro"));

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaVaiTro");

                    b.ToTable("VaiTro");

                    b.HasData(
                        new
                        {
                            MaVaiTro = 1,
                            TenVaiTro = "Admin"
                        },
                        new
                        {
                            MaVaiTro = 2,
                            TenVaiTro = "GiaoVien"
                        },
                        new
                        {
                            MaVaiTro = 3,
                            TenVaiTro = "HocSinh"
                        });
                });

            modelBuilder.Entity("WebQLThiTracNghiem.Models.HocSinh", b =>
                {
                    b.HasOne("WebQLThiTracNghiem.Models.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebQLThiTracNghiem.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");

                    b.Navigation("NguoiDung");
                });
#pragma warning restore 612, 618
        }
    }
}
